development:
  adapter: postgresql
  encoding: unicode
  database: inventory_system_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: inventory_system_test
  pool: 5
  username:
  password:
